version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
  db:
    image: "postgres:14-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker
      PGDATA : /app
    ports:
      - "8001:5432"
    volumes:
      - ./app:/var/lib/postgresql/data
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql